### PR TITLE
fix-issue-24 - isAllowed=false and isDisallowed=false

### PR DESCRIPTION
**Pull request by JanPetterMG**
Sometimes, when the robots.txt file cannot be parsed properly, we get problematic results. This may happen on bad robots.txt files, and doesn't always mean there is a issue with the code.

For example:
isAllowed('/') = (bool) false 
and 
isDisallowed('/') = (bool) false

With this fix, its now returning a NULL value in case of parsing errors.

### CODE REVIEW

**Comment by t1gor** [comment]
Please fix the tests and I will accept the code gladly!

https://travis-ci.org/t1gor/Robots.txt-Parser-Class/jobs/82985193#L211

**Comment by JanPetterMG** [comment]
Please say the tests are ok :) first time writing a test, that's why xD

The checks is failing because of issue #26, when that one is in place, the code in this pull request will no longer fail...

**Comment by JanPetterMG** [comment]
Hehe, I have too many branches I think, keep merging the patches with master, but I shuldn't. The code related to this issue is from master branch, the other pull requests are from patches...
Just look at the changed code, and you'll see, it's not that much changes...

**Comment by JanPetterMG** [comment]
The Travis CI build is failing because I changed the code to **throw an exception** instead of returning a **invalid result** (isallowed=false and isdisallowed=false)...
Therefore there actually isn't anything wrong with my submitted code, instead it points out an old bug, which was the reason for this pull request in the first place.

We *could* edit the test, so that it passes, but it does nothing else than hide the problem...

I therefore suggest you accept this pull request.

**Comment by t1gor** [comment]
wow ... Seems like you're really into it :) thanks a lot! I will accept the request and fix the test myself.

For future: if you are changing the code to throw an exception - it's obviously the right time to change the test :)

**Pull request merged**
