### PR TITLE
Fixed half of PHPCS problems, enabled composer test

### PR DESCRIPTION
**Pull request by szepeviktor**
The other half:
```
----------------------------------------------------------------------
FOUND 78 ERRORS AND 28 WARNINGS AFFECTING 101 LINES
----------------------------------------------------------------------
  10 | WARNING | Line exceeds 85 characters; contains 90 characters
  13 | WARNING | Line exceeds 85 characters; contains 87 characters
  21 | WARNING | PHP version not specified
  21 | ERROR   | Missing @category tag in file comment
  21 | ERROR   | Missing @package tag in file comment
  21 | ERROR   | Missing @license tag in file comment
  22 | ERROR   | Missing class doc comment
  45 | ERROR   | Private member variable "state" must be prefixed
     |         | with an underscore
  48 | ERROR   | Private member variable "url" must be prefixed with
     |         | an underscore
  51 | ERROR   | Private member variable "userAgent" must be prefixed
     |         | with an underscore
  52 | ERROR   | Private member variable "userAgent_groups" must be
     |         | prefixed with an underscore
  53 | ERROR   | Private member variable "userAgent_match" must be
     |         | prefixed with an underscore
  56 | ERROR   | Private member variable "content" must be prefixed
     |         | with an underscore
 114 | ERROR   | Missing @return tag in function comment
 122 | ERROR   | Missing @return tag in function comment
 130 | ERROR   | Missing @return tag in function comment
 143 | ERROR   | Missing @return tag in function comment
 153 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 194 | WARNING | Line exceeds 85 characters; contains 107 characters
 207 | WARNING | Line exceeds 85 characters; contains 91 characters
 302 | ERROR   | Private method name
     |         | "RobotsTxtParser::addValueToDirective" must be
     |         | prefixed with an underscore
 337 | ERROR   | Missing parameter comment
 338 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 347 | WARNING | Line exceeds 85 characters; contains 183 characters
 355 | ERROR   | Missing parameter comment
 356 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 365 | WARNING | Line exceeds 85 characters; contains 95 characters
 377 | ERROR   | Private method name
     |         | "RobotsTxtParser::setCurrentUserAgent" must be
     |         | prefixed with an underscore
 412 | ERROR   | Private method name
     |         | "RobotsTxtParser::explodeUserAgent" must be prefixed
     |         | with an underscore
 428 | ERROR   | Missing parameter comment
 429 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 431 | ERROR   | Private method name
     |         | "RobotsTxtParser::stripUserAgentVersion" must be
     |         | prefixed with an underscore
 442 | ERROR   | Missing parameter comment
 443 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 445 | ERROR   | Private method name "RobotsTxtParser::addRule" must
     |         | be prefixed with an underscore
 455 | WARNING | Line exceeds 85 characters; contains 86 characters
 464 | ERROR   | Private method name "RobotsTxtParser::addCleanParam"
     |         | must be prefixed with an underscore
 469 | WARNING | Line exceeds 85 characters; contains 106 characters
 478 | ERROR   | Private method name "RobotsTxtParser::addHost" must
     |         | be prefixed with an underscore
 487 | WARNING | Line exceeds 85 characters; contains 89 characters
 502 | ERROR   | Private method name "RobotsTxtParser::addSitemap"
     |         | must be prefixed with an underscore
 514 | ERROR   | Missing parameter comment
 515 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 517 | ERROR   | Private method name "RobotsTxtParser::convert" must
     |         | be prefixed with an underscore
 556 | ERROR   | Missing parameter comment
 557 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 593 | ERROR   | Missing parameter comment
 594 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 609 | ERROR   | Missing parameter comment
 610 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 624 | ERROR   | Missing parameter comment
 625 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 627 | ERROR   | Private method name
     |         | "RobotsTxtParser::explodeCleanParamRule" must be
     |         | prefixed with an underscore
 635 | WARNING | Line exceeds 85 characters; contains 130 characters
 645 | WARNING | Line exceeds 85 characters; contains 118 characters
 649 | ERROR   | Parameter tags must be defined first in a doc
     |         | comment
 649 | ERROR   | Missing parameter comment
 650 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 652 | ERROR   | Protected method name "RobotsTxtParser::encode_url"
     |         | is not in camel caps format
 675 | WARNING | Line exceeds 85 characters; contains 96 characters
 682 | ERROR   | Missing parameter comment
 683 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 690 | WARNING | Line exceeds 85 characters; contains 90 characters
 692 | WARNING | Line exceeds 85 characters; contains 89 characters
 700 | WARNING | Line exceeds 85 characters; contains 135 characters
 707 | ERROR   | Missing parameter comment
 708 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 710 | ERROR   | Private method name "RobotsTxtParser::getPath" must
     |         | be prefixed with an underscore
 724 | ERROR   | Missing parameter comment
 725 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 727 | ERROR   | Private method name "RobotsTxtParser::isValidScheme"
     |         | must be prefixed with an underscore
 740 | WARNING | Line exceeds 85 characters; contains 92 characters
 741 | ERROR   | Parameter tags must be grouped together in a doc
     |         | comment
 741 | ERROR   | Missing parameter comment
 742 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 744 | ERROR   | Private method name
     |         | "RobotsTxtParser::isValidHostName" must be prefixed
     |         | with an underscore
 746 | WARNING | Line exceeds 85 characters; contains 110 characters
 748 | WARNING | Line exceeds 85 characters; contains 87 characters
 757 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 763 | WARNING | Line exceeds 85 characters; contains 102 characters
 771 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 777 | WARNING | Line exceeds 85 characters; contains 105 characters
 786 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 796 | WARNING | Line exceeds 85 characters; contains 88 characters
 815 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 821 | WARNING | Line exceeds 85 characters; contains 88 characters
 841 | ERROR   | Missing parameter comment
 842 | ERROR   | Missing parameter comment
 843 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 845 | ERROR   | Private method name
     |         | "RobotsTxtParser::checkBasicRule" must be prefixed
     |         | with an underscore
 867 | ERROR   | Missing parameter comment
 868 | ERROR   | Missing parameter comment
 869 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 871 | ERROR   | Private method name
     |         | "RobotsTxtParser::checkCleanParamRule" must be
     |         | prefixed with an underscore
 892 | ERROR   | Missing parameter comment
 893 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 895 | ERROR   | Private method name "RobotsTxtParser::checkHostRule"
     |         | must be prefixed with an underscore
 898 | WARNING | Line exceeds 85 characters; contains 98 characters
 904 | WARNING | Line exceeds 85 characters; contains 89 characters
 910 | WARNING | Line exceeds 85 characters; contains 95 characters
 924 | ERROR   | Private method name
     |         | "RobotsTxtParser::checkHttpStatusCodeRule" must be
     |         | prefixed with an underscore
 968 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
 985 | WARNING | Line exceeds 85 characters; contains 93 characters
 986 | WARNING | Line exceeds 85 characters; contains 133 characters
 996 | ERROR   | Missing parameter comment
 997 | ERROR   | Tag cannot be grouped with parameter tags in a doc
     |         | comment
----------------------------------------------------------------------
```

### CODE REVIEW

**Comment by szepeviktor** [comment]
If you add `editorconfig.org`
```
# editorconfig.org

root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.php]
indent_size = 4
```
GitHub will display nice 4-wide tabs.
Actually tabs are no more ....

**Comment by LeMoussel** [comment]
What rules do you use with PHPHCS?

**Comment by szepeviktor** [comment]
I've given no options to `phpcs`. I think it is the PEAR standard...
https://github.com/squizlabs/PHP_CodeSniffer/wiki#example

**Comment by szepeviktor** [comment]
Thanks.

Please help me in the prettify issue.

**Comment by t1gor** [comment]
Why PEAR, if that's not a secret?

**Comment by szepeviktor** [comment]
That is PHPCS' default.

**Comment by szepeviktor** [comment]
Any fixed code-styling is much better than a mixed one.

**Comment by t1gor** [comment]
> Any fixed code-styling is much better than a mixed one.

I totally agree on this one, but would personally prefer PSR.

**Comment by szepeviktor** [comment]
You could use `php php-cs-fixer.phar fix /path/to/project --level=psr2`
https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage

**Comment by JanPetterMG** [comment]
I'll just re-arranged the code based on usage. There is a possibility that some code-styling also is changed...
It's much better now, easier to read and understand how the code is connected...

Didn't run any ``php-cs-fixer``, as I don't think it's needed anymore. It's probably only going to complain about line lengths anyway...
If this is good enough, is up to you to decide. Do whatever you want with the code...

**Pull request merged**
