### PR TITLE
Replaces #35: User-agent case-insensitive

### PR DESCRIPTION
**Pull request by JanPetterMG**
Replaces #35 User-agent case-insensitive (was based on old code, required manual merge).
Also did a small doc correction. That's all.

### CODE REVIEW

**Comment by t1gor** [comment]
Great job!

**Comment by JanPetterMG** [comment]
Any reason this pull request was closed without merge?
The one it replaced wasn't merged either (I closed it myself yesterday when I wrote this replacement, to not make any confusions).

Also the build is failing because of a missing fix witch this pull-request contains (happen after #31 was merged). https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt#example-path-matches

Feel free to not merge this one, but then I want to know whats wrong with it.

**Comment by JanPetterMG** [comment]
BUMP! How to re-open this request???

**Comment by t1gor** [comment]
Sorry, got distracted a bit :)

**Pull request merged**
